# Generated by Django 5.2.17 on 2026-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='currency',
            field=models.CharField(default='AED', max_length=3),
        ),
    ]
